/**
 * Action types for the chat state management
 */
export enum ActionType {
  // Message related actions
  SET_MESSAGES = 'SET_MESSAGES',
  ADD_MESSAGE = 'ADD_MESSAGE',
  SET_LOADING = 'SET_LOADING',
  
  // API and model related actions
  SET_MODEL = 'SET_MODEL',
  TOGGLE_API_KEY_MODAL = 'TOGGLE_API_KEY_MODAL',
  SET_API_KEY = 'SET_API_KEY',
  
  // Conversation management actions
  SET_CONVERSATION_LIST_VISIBILITY = 'SET_CONVERSATION_LIST_VISIBILITY',
  SET_ACTIVE_CONVERSATION = 'SET_ACTIVE_CONVERSATION',
  UPDATE_CONVERSATIONS = 'UPDATE_CONVERSATIONS',
  SET_CONVERSATION_TITLE = 'SET_CONVERSATION_TITLE',
  
  // System prompt actions
  TOGGLE_SYSTEM_PROMPT_EDITOR = 'TOGGLE_SYSTEM_PROMPT_EDITOR',
  SET_SYSTEM_PROMPT = 'SET_SYSTEM_PROMPT',
  
  // Voice related actions
  TOGGLE_VOICE_ENABLED = 'TOGGLE_VOICE_ENABLED',
  SET_LISTENING = 'SET_LISTENING',
  SET_SPEAKING = 'SET_SPEAKING'
}